### ISSUE TITLE
This is not working in a ionic3

### ISSUE THREAD

**Issue by roshani4** [PrithiviRajG/Ionic-3-Native-Date-Picker-example#2]

**Comment by PrithiviRajG** [comment]
Share the error message or what is the problem you are facing?

**Comment by roshani4** [comment]
Can't bind to 'ng-model' since it isn't a known property of 'span'. ("ding-left: 60px" ion-datepicker  [(value)]="localDate" [min]="localDate" clear class="ScheduleDate" [ERROR ->][(ng-model)]="my.dobr">
    <span>{{localDate | date}} <ion-icon name="clipboard" item-left ></ion-ic"): ng:///AppModule/ClientPage.html@33:120
    at syntaxError (http://localhost:8100/build/vendor.js:81645:34)
    at TemplateParser.parse (http://localhost:8100/build/vendor.js:105833:19)
    at JitCompiler._parseTemplate (http://localhost:8100/build/vendor.js:115788:37)
    at JitCompiler._compileTemplate (http://localhost:8100/build/vendor.js:115763:23)
    at http://localhost:8100/build/vendor.js:115664:62
    at Set.forEach (<anonymous>)
    at JitCompiler._compileComponents (http://localhost:8100/build/vendor.js:115664:19)
    at http://localhost:8100/build/vendor.js:115534:19
    at Object.then (http://localhost:8100/build/vendor.js:81634:77)
    at JitCompiler._compileModuleAndComponents (http://localhost:8100/build/vendor.js:115533:26)
